/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Conntentpanel;
import dashboard.MainMenu;
//import static java.awt.Image.SCALE_SMOOTH;
//import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.Statement;
//import java.sql.*;
//import java.util.logging.Level;
//import java.util.logging.Logger;
/**
 *
 * @author Durai
 */
public class ItemDisplay extends javax.swing.JPanel {
    public static productPanel p1 = new productPanel();
    public String instruction,modelno,minrate,maxrate;
    public  int USERIDPRODUCT;
    /**
     * Creates new form NewJPanel
     */
    public ItemDisplay() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photo = new javax.swing.JLabel();
        productname = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        action = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 255, 204));

        photo.setForeground(new java.awt.Color(255, 255, 204));
        photo.setText("jLabel1");

        productname.setBackground(new java.awt.Color(255, 255, 255));
        productname.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        productname.setForeground(new java.awt.Color(181, 184, 190));
        productname.setText("    name");
        productname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        productname.setOpaque(true);

        name.setEditable(false);
        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(181, 184, 190));
        name.setText("   name");
        name.setOpaque(true);

        jLabel2.setText("likes     :");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setText("10k");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        description.setBackground(new java.awt.Color(255, 255, 255));
        description.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        description.setForeground(new java.awt.Color(181, 184, 190));
        description.setText("     description");
        description.setOpaque(true);

        action.setBackground(new java.awt.Color(20, 22, 30));
        action.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        action.setForeground(new java.awt.Color(255, 255, 255));
        action.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/details (1).png"))); // NOI18N
        action.setText("Product Details");
        action.setBorder(null);
        action.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        action.setIconTextGap(30);
        action.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(productname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(action, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(action, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public static productPanel panel()
    {
        return p1;
    }
    private void actionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionActionPerformed
        // TODO add your handling code here:
        //productPanel p1 = new productPanel();
       
                   
            p1.modelname.setText(this.name.getText());
            p1.photo.setIcon(this.photo.getIcon());
            p1.description.setText(this.description.getText());
            p1.instruction.setText(this.instruction);
            p1.minrate.setText(this.minrate);
            p1.maxrate.setText(this.maxrate);
            p1.USERPRODUCTID = this.USERIDPRODUCT;
            
            
       
        MainMenu.jTabbedPane1.add(p1);
        MainMenu.jTabbedPane1.setSelectedComponent(p1);
       
        
    }//GEN-LAST:event_actionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton action;
    public javax.swing.JLabel description;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField name;
    public javax.swing.JLabel photo;
    public javax.swing.JLabel productname;
    // End of variables declaration//GEN-END:variables
}
