/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Conntentpanel;

import ChartFram.BillFrame;
import dashboard.MainMenu;
import java.awt.Color;
//import Conntentpanel.ItemDisplay.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

//import dashboard.MainMenu.*;
/**
 *
 * @author Durai
 */
public class productPanel extends javax.swing.JPanel {
    
    BillFrame ch = new BillFrame();
    public  int USERPRODUCTID;
    /**
     * Creates new form productPanel
     */
    public productPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        modelname_l = new javax.swing.JLabel();
        productNmae_l = new javax.swing.JLabel();
        minrate_l = new javax.swing.JLabel();
        maxrate = new javax.swing.JLabel();
        instruction_l = new javax.swing.JLabel();
        description_l = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        placeOrder_b = new javax.swing.JButton();
        Back_l = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1080, 689));

        photo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jSeparator1.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator1.setOpaque(true);

        modelname_l.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        modelname_l.setText("        MODEL NO");
        modelname_l.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 2, true));
        modelname_l.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                modelname_lFocusGained(evt);
            }
        });

        productNmae_l.setBackground(new java.awt.Color(255, 255, 255));
        productNmae_l.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        productNmae_l.setForeground(new java.awt.Color(45, 5, 41));
        productNmae_l.setText("       PRODUCT NAME");
        productNmae_l.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 1, true));
        productNmae_l.setOpaque(true);

        minrate_l.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        minrate_l.setForeground(new java.awt.Color(51, 0, 51));
        minrate_l.setText("        MINIMUM RATE");
        minrate_l.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 2, true));

        maxrate.setBackground(new java.awt.Color(255, 255, 255));
        maxrate.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        maxrate.setForeground(new java.awt.Color(0, 0, 51));
        maxrate.setText("      MAX RATE");
        maxrate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 2, true));

        instruction_l.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        instruction_l.setForeground(new java.awt.Color(51, 0, 51));
        instruction_l.setText("     iNSRTUCTION");
        instruction_l.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 2, true));

        description_l.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        description_l.setForeground(new java.awt.Color(51, 0, 51));
        description_l.setText("        DESCRIPTION");
        description_l.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 1, true));

        jLabel11.setForeground(new java.awt.Color(181, 184, 142));
        jLabel11.setText("jLabel11");
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 2, true));

        placeOrder_b.setBackground(new java.awt.Color(20, 22, 30));
        placeOrder_b.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        placeOrder_b.setForeground(new java.awt.Color(204, 255, 255));
        placeOrder_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order (1).png"))); // NOI18N
        placeOrder_b.setText("place order");
        placeOrder_b.setBorder(null);
        placeOrder_b.setIconTextGap(25);
        placeOrder_b.setOpaque(true);
        placeOrder_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrder_bActionPerformed(evt);
            }
        });

        Back_l.setBackground(new java.awt.Color(20, 22, 30));
        Back_l.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Back_l.setForeground(new java.awt.Color(255, 255, 255));
        Back_l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back (1).png"))); // NOI18N
        Back_l.setText("Back");
        Back_l.setBorder(null);
        Back_l.setIconTextGap(55);
        Back_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_lActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modelname_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productNmae_l, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(minrate_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxrate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(instruction_l, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(placeOrder_b, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                        .addComponent(Back_l, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(description_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(photo, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(modelname_l, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productNmae_l, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(minrate_l, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maxrate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(description_l, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(instruction_l, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placeOrder_b, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back_l, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Back_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_lActionPerformed
        // TODO add your handling code here:
        photo.setText("hello");
        
        MainMenu.jTabbedPane1.remove(ItemDisplay.panel());
      
    }//GEN-LAST:event_Back_lActionPerformed

    private void placeOrder_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrder_bActionPerformed
        // TODO add your handling code here:
        
        try
        {
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/uzhavan","root","");
            String sql = "SELECT name,phonenumber,emailid from user where  user.user_id = "+USERPRODUCTID;
            PreparedStatement stmt =con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            if(rs.next())
            {
                BillFrame.name.setText(rs.getString(1));
                BillFrame.phone.setText(rs.getString(2));
                BillFrame.address.setText(rs.getString(3));
                BillFrame.product.setText(this.modelname_l.getText());
                BillFrame.model.setText(this.modelname_l.getText());
                BillFrame.price.setText(this.maxrate.getText());
                ch.setVisible(true);
               // MainMenu.mainMenuform.setVisible(false);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Data cannot display");
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_placeOrder_bActionPerformed

    private void modelname_lFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modelname_lFocusGained
        // TODO add your handling code here:
         
    }//GEN-LAST:event_modelname_lFocusGained
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_l;
    public javax.swing.JLabel description_l;
    public javax.swing.JLabel instruction_l;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel maxrate;
    public javax.swing.JLabel minrate_l;
    public javax.swing.JLabel modelname_l;
    public javax.swing.JLabel photo;
    private javax.swing.JButton placeOrder_b;
    private javax.swing.JLabel productNmae_l;
    // End of variables declaration//GEN-END:variables
}
