/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Conntentpanel;

import ChartFram.BillFrame;
import dashboard.MainMenu;
import java.awt.Color;
//import Conntentpanel.ItemDisplay.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

//import dashboard.MainMenu.*;
/**
 *
 * @author Durai
 */
public class productPanel extends javax.swing.JPanel {
    
    BillFrame ch = new BillFrame();
    public  int USERPRODUCTID;
    /**
     * Creates new form productPanel
     */
    public productPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        modelname_l = new javax.swing.JLabel();
        productNmae_l = new javax.swing.JLabel();
        minrate_l = new javax.swing.JLabel();
        maxrate = new javax.swing.JLabel();
        instruction_l = new javax.swing.JLabel();
        description_l = new javax.swing.JLabel();
        placeOrder_b = new javax.swing.JButton();
        Back_l = new javax.swing.JButton();
        description_l1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1080, 689));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2022-12-14 at 20.52.24.jpg"))); // NOI18N
        photo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, 309, -1));

        jSeparator1.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 6, 3, 699));

        modelname_l.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        modelname_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modelname_l.setText("SVE15127CNB");
        modelname_l.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 2, true));
        modelname_l.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                modelname_lFocusGained(evt);
            }
        });
        add(modelname_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 204, 407, 76));

        productNmae_l.setBackground(new java.awt.Color(255, 255, 255));
        productNmae_l.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        productNmae_l.setForeground(new java.awt.Color(45, 5, 41));
        productNmae_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productNmae_l.setText("Spray Drone");
        productNmae_l.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 1, true));
        productNmae_l.setOpaque(true);
        add(productNmae_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 298, 407, 70));

        minrate_l.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        minrate_l.setForeground(new java.awt.Color(51, 0, 51));
        minrate_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minrate_l.setText("Starts 1,000rs");
        minrate_l.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 2, true));
        add(minrate_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 386, 407, 73));

        maxrate.setBackground(new java.awt.Color(255, 255, 255));
        maxrate.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        maxrate.setForeground(new java.awt.Color(0, 0, 51));
        maxrate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxrate.setText(" max 4,000 rs");
        maxrate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 2, true));
        add(maxrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 477, 407, 82));

        instruction_l.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        instruction_l.setForeground(new java.awt.Color(51, 0, 51));
        instruction_l.setText("Skilled drone handler is not needed. It fully automated drone");
        add(instruction_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 578, 70));

        description_l.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        description_l.setForeground(new java.awt.Color(51, 0, 51));
        description_l.setText("This product can able to spray 1-acer within 20 minutes ");
        add(description_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 578, 54));

        placeOrder_b.setBackground(new java.awt.Color(20, 22, 30));
        placeOrder_b.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        placeOrder_b.setForeground(new java.awt.Color(204, 255, 255));
        placeOrder_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order (1).png"))); // NOI18N
        placeOrder_b.setText("place order");
        placeOrder_b.setBorder(null);
        placeOrder_b.setIconTextGap(25);
        placeOrder_b.setOpaque(true);
        placeOrder_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrder_bActionPerformed(evt);
            }
        });
        add(placeOrder_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 593, 203, 54));

        Back_l.setBackground(new java.awt.Color(20, 22, 30));
        Back_l.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Back_l.setForeground(new java.awt.Color(255, 255, 255));
        Back_l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back (1).png"))); // NOI18N
        Back_l.setText("Back");
        Back_l.setBorder(null);
        Back_l.setIconTextGap(55);
        Back_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_lActionPerformed(evt);
            }
        });
        add(Back_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 593, 182, 54));

        description_l1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        description_l1.setForeground(new java.awt.Color(51, 0, 51));
        description_l1.setText("It consumes one litre of pesticides for 1-acer");
        add(description_l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 578, 54));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 570, 110));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel2.setText("It uses GPS for capurating the field. It will accruately spray the pesticides");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 620, 90));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 620, 90));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel4.setText("Discription");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 210, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void Back_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_lActionPerformed
        // TODO add your handling code here:
        photo.setText("hello");
        
        MainMenu.jTabbedPane1.remove(ItemDisplay.panel());
      
    }//GEN-LAST:event_Back_lActionPerformed

    private void placeOrder_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrder_bActionPerformed
        // TODO add your handling code here:
        
        try
        {
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/uzhavan","root","");
            String sql = "SELECT name,phonenumber,emailid from user where  user.user_id = "+USERPRODUCTID;
            PreparedStatement stmt =con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            if(rs.next())
            {
                BillFrame.name.setText(rs.getString(1));
                BillFrame.phone.setText(rs.getString(2));
                BillFrame.address.setText(rs.getString(3));
                BillFrame.product.setText(this.modelname_l.getText());
                BillFrame.model.setText(this.modelname_l.getText());
                BillFrame.price.setText(this.maxrate.getText());
                ch.setVisible(true);
               // MainMenu.mainMenuform.setVisible(false);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Data cannot display");
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_placeOrder_bActionPerformed

    private void modelname_lFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modelname_lFocusGained
        // TODO add your handling code here:
         
    }//GEN-LAST:event_modelname_lFocusGained
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_l;
    public javax.swing.JLabel description_l;
    public javax.swing.JLabel description_l1;
    public javax.swing.JLabel instruction_l;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel maxrate;
    public javax.swing.JLabel minrate_l;
    public javax.swing.JLabel modelname_l;
    public javax.swing.JLabel photo;
    private javax.swing.JButton placeOrder_b;
    private javax.swing.JLabel productNmae_l;
    // End of variables declaration//GEN-END:variables
}
